### ISSUE TITLE
<google-recaptcha> is not working for me in chrome. same code is working fine in IE + firefox + safari. getting Error : "Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame""

### ISSUE THREAD

**Issue by vyomabypt** [Zecat/google-recaptcha#7]
Hi,

Here, i have uploaded my source code.

i have written captcha code in my-samplepage.html.

That same code is working fine in IE + Firefox + safari but getting below error in chrome.
```

Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at lb.t.tZ (https://www.gstatic.com/recaptcha/api2/v1548052318968/recaptcha__en.js:515:271)
    at yj (https://www.gstatic.com/recaptcha/api2/v1548052318968/recaptcha__en.js:522:135)
    at Object.init (https://www.gstatic.com/recaptcha/api2/v1548052318968/recaptcha__en.js:527:434)
    at https://www.google.com/recaptcha/api2/bframe?hl=en&v=v1548052318968&k=6LcI04UUAAAAADBTEtJ0exAwAe57vkNqObj6tKIQ&cb=r1oyt78mj7bb:184:30
```

https://github.com/cbalit/re-captcha/files/2821304/firstdemo.zip

Could you please assist me here?

Thanks in Advanced!

**Comment by apesteguy** [comment]
Hey @vyomabypt did you find a solution ? I am facing the same issue :-)

**Comment by vpalos** [comment]
Hi, after some searching I found this: https://medium.com/@tomas_26986/using-recaptcha-with-react-and-shadow-dom-abfd19fa03a

So, the issue is that (perhaps) you're rendering the reCaptcha inside a Shadow DOM element.
This was exactly my case.
